#!/usr/bin/env ruby
gem = Gem::Specification::load("rumrunner.gemspec")

rum gem.name do
  tag gem.version

  env :RUBY_TAG => ENV["RUBY_TAG"] || "latest"

  stage :build
  stage :test => :build
  stage :release => :test do
    build_arg :RUBYGEMS_API_KEY
  end

  artifact "pkg/#{gem.full_name}.gem" => :build

  default "pkg/#{gem.full_name}.gem"
end
